# .github/workflows/generate-readme.yml
name: 自动生成协议列表
on:
  push:
    branches: [ main ]
    paths:
      - '*.html'
      - 'generate_readme.py'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 运行脚本
        run: python generate_readme.py

      - name: 自动提交
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "自动更新协议列表"
